// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "hello", input: Info, result: string } | 
        { key: "user.list", input: never, result: null[] } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type Info = { name: string; message: string }
